### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by farteryhr** [Tidyzq/galaxies-puzzle-solver#1]
![image](https://github.com/user-attachments/assets/83331416-e8e8-4992-ab4c-f396f4de8489)

the solution to this is non-unique, but obviously exists (just draw a big N). does this solver require the puzzle to be unique solution to output one solution?

**Comment by Tidyzq** [comment]
Your puzzle is invalid as each region must contains exactly one white circle center point, the regions on the corners violates this rule. In anothor words, each region must be continuous.
This solver cannot handle invalid puzzles.

**Comment by farteryhr** [comment]
![image](https://github.com/user-attachments/assets/87889aca-ccff-4517-a9f4-1c85a3280c67)
![image](https://github.com/user-attachments/assets/8bccd62f-ebe5-4848-b16f-b7d27d11e2f1)
![image](https://github.com/user-attachments/assets/99989db7-94da-4cd5-b125-908a896cedb0)
this puzzle is solvable, there are just many solutions. so the question is still: does this solver require the puzzle to have unique solution?
the solver used to produce these images: https://util.in:8102/

**Comment by Tidyzq** [comment]
You are right, this solver have some issue in your case, just fixed in 6cb14f66589d928916313e7aef16eb57b34ba3e6

This issue is due to incorrect marking for possible center of the cell, rather than lake of the ability to solve puzzles with multiple solutions. This solver includes a DFS (Depth-First Search) procedure and is guaranteed to return a solution, even if the puzzle has many possible answers.

Thanks for your report.
